// src/components/schedule/ScheduleItem.jsx
/**
 * ScheduleItem.jsx - Single schedule list item
 */

import React from 'react'
import { useCategoryStore } from '@/stores/categoryStore'
import { isPast as checkIsPast } from '@/utils/date'

export default function ScheduleItem({
    schedule,
    showCheckbox = true,
    onCLick,
    onEdit,
    onDelete,
    onToggleComplete
}) {
    const categoryStore = useCategoryStore()

    const category = categoryStore.getCategoryById(schedule.category)
    const categoryColor = category?.color || '#B0B0B0'
    const categoryName = category?.name || 'その他'
    const isPast = checkIsPast(schedule.startDate)

    const timeDisplay = schedule.isAllDay
        ? '終日'
        : `${schedule.startTime} - ${schedule.endTime}`

    const classNames = [
        'schedule-item',
        schedule.isCompleted ? 'is-completed' : '',
        isPast ? 'is-past' : ''
    ].filter(Boolean).join(' ')

    return (
        <div
            className={classNames}
            style={{ borderLeftColor: categoryColor }}
            onClick={() => onCLick && onCLick(schedule)}
        >
            <div className="schedule-time">
                <span>🕐</span>
                <span>{timeDisplay}</span>
            </div>

            <div className="schedule-content">
                <h4 className="schedule-title">{schedule.title}</h4>
                {schedule.description && (
                    <p className="schedule-description">{schedule.description}</p>
                )}

                <div className="schedule-meta">
                    <span className="tag tag-outline" style={{ color: categoryColor, borderColor: categoryColor }}>
                        {categoryName}
                    </span>
                    {schedule.tags && schedule.tags.map(tag => (
                        <span key={tag} className="tag tag-outline">{tag}</span>
                    ))}
                    {schedule.reminder?.enabled && <span>🔔</span>}
                </div>
            </div>

            <div className="schedule-status">
                {showCheckbox ? (
                    <input
                        type="checkbox"
                        checked={!!schedule.isCompleted}
                        onChange={e => { e.stopPropagation(); onToggleComplete && onToggleComplete(schedule) }}
                        onClick={e => e.stopPropagation()}
                        className="schedule-checkbox"
                    />
                ) : (
                    <span className="arrow-icon">›</span>
                )}
            </div>

            <div className="schedule-swipe-actions">
                <button
                    className="btn btn-primary btn-sm"
                    onClick={e => { e.stopPropagation(); onEdit && onEdit(schedule) }}
                >
                    編集
                </button>
                <button
                    className="btn btn-danger btn-sm"
                    onClick={e => { e.stopPropagation(); onDelete && onDelete(schedule) }}
                >
                    削除
                </button>
            </div>
        </div>
    )
}

// src/components/schedule/ScheduleItem.vue
<template>
  <van-swipe-cell :disabled="!allowSwipe">
    <div
      class="schedule-item"
      :class="{ 'is-completed': schedule.isCompleted, 'is-past': isPast }"
      :style="{ borderLeftColor: categoryColor }"
      @click="$emit('click', schedule)"
    >
      <!-- Time -->
      <div class="schedule-time">
        <van-icon name="clock-o" size="14" />
        <span>{{ timeDisplay }}</span>
      </div>

      <!-- Content -->
      <div class="schedule-content">
        <h4 class="schedule-title">
          {{ schedule.title }}
        </h4>
        <p v-if="schedule.description" class="schedule-description">
          {{ schedule.description }}
        </p>

        <!-- Meta info -->
        <div class="schedule-meta">
          <van-tag
            :color="categoryColor"
            plain
            size="small"
          >
            {{ categoryName }}
          </van-tag>

          <van-tag
            v-for="tag in schedule.tags"
            :key="tag"
            plain
            size="small"
          >
            {{ tag }}
          </van-tag>

          <van-icon
            v-if="schedule.reminder?.enabled"
            name="bell-o"
            size="14"
            color="var(--warning-color)"
          />
        </div>
      </div>

      <!-- Status icon -->
      <div class="schedule-status">
        <van-checkbox
          v-if="showCheckbox"
          :model-value="schedule.isCompleted"
          @click.stop="$emit('toggle-complete', schedule)"
        />
        <van-icon
          v-else
          name="arrow"
          size="16"
          color="var(--text-light)"
        />
      </div>
    </div>

    <!-- Swipe actions -->
    <template #right>
      <van-button
        square
        text="編集"
        type="primary"
        class="swipe-button"
        @click="$emit('edit', schedule)"
      />
      <van-button
        square
        text="削除"
        type="danger"
        class="swipe-button"
        @click="$emit('delete', schedule)"
      />
    </template>
  </van-swipe-cell>
</template>

<script setup>
import { computed } from 'vue'
import { useCategoryStore } from '@/stores/category'
import { isPast as checkIsPast } from '@/utils/date'

// Props
const props = defineProps({
  schedule: {
    type: Object,
    required: true
  },
  showCheckbox: {
    type: Boolean,
    default: true
  },
  allowSwipe: {
    type: Boolean,
    default: true
  }
})

// Emits
defineEmits(['click', 'edit', 'delete', 'toggle-complete'])

// Store
const categoryStore = useCategoryStore()

// Computed
const categoryColor = computed(() => {
  const category = categoryStore.getCategoryById(props.schedule.category)
  return category?.color || '#B0B0B0'
})

const categoryName = computed(() => {
  const category = categoryStore.getCategoryById(props.schedule.category)
  return category?.name || 'その他'
})

const timeDisplay = computed(() => {
  if (props.schedule.isAllDay) {
    return '終日'
  }
  return `${props.schedule.startTime} - ${props.schedule.endTime}`
})

const isPast = computed(() => {
  return checkIsPast(props.schedule.startDate)
})
</script>

<style scoped>
.schedule-item {
  display: flex;
  align-items: flex-start;
  gap: var(--spacing-md);
  padding: var(--spacing-md);
  background: var(--bg-card);
  border-left: 4px solid var(--primary-color);
  border-radius: var(--radius-md);
  cursor: pointer;
  transition: all var(--transition-fast);
}

.schedule-item:hover {
  background: var(--bg-hover);
  transform: translateX(2px);
}

.schedule-item.is-completed {
  opacity: 0.6;
}

.schedule-item.is-completed .schedule-title {
  text-decoration: line-through;
  color: var(--text-secondary);
}

.schedule-item.is-past {
  opacity: 0.7;
}

/* Time */
.schedule-time {
  display: flex;
  align-items: center;
  gap: 4px;
  min-width: 80px;
  font-size: var(--font-sm);
  color: var(--text-secondary);
  font-weight: var(--font-medium);
}

/* Content */
.schedule-content {
  flex: 1;
  min-width: 0;
}

.schedule-title {
  font-size: var(--font-base);
  font-weight: var(--font-semibold);
  color: var(--text-primary);
  margin-bottom: 4px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.schedule-description {
  font-size: var(--font-sm);
  color: var(--text-secondary);
  margin-bottom: var(--spacing-sm);
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}

.schedule-meta {
  display: flex;
  flex-wrap: wrap;
  gap: var(--spacing-xs);
  align-items: center;
}

/* Status */
.schedule-status {
  display: flex;
  align-items: center;
}

/* Swipe buttons */
.swipe-button {
  height: 100%;
}
</style>
