// src/components/schedule/ScheduleEditor.vue
<template>
  <div class="schedule-editor">
    <van-form @submit="handleSubmit">
      <!-- Title -->
      <van-field
        v-model="form.title"
        label="タイトル"
        placeholder="タイトルを入力してください"
        required
        :rules="[{ required: true, message: 'タイトルを入力してください' }]"
        maxlength="50"
        show-word-limit
      />

      <!-- Description -->
      <van-field
        v-model="form.description"
        label="説明"
        type="textarea"
        placeholder="説明を入力してください（任意）"
        rows="3"
        autosize
        maxlength="200"
        show-word-limit
      />

      <!-- Start Date -->
      <van-field
        label="開始日"
        :model-value="formatDate(form.startDate)"
        placeholder="開始日を選択してください"
        readonly
        required
        clickable
        @click="showStartDatePicker = true"
      >
        <template #left-icon>
          <van-icon name="calendar-o" />
        </template>
      </van-field>

      <!-- Start Time (hidden if all-day) -->
      <van-field
        v-if="!form.isAllDay"
        label="開始時刻"
        :model-value="form.startTime"
        placeholder="開始時刻を選択してください"
        readonly
        clickable
        @click="showStartTimePicker = true"
      >
        <template #left-icon>
          <van-icon name="clock-o" />
        </template>
      </van-field>

      <!-- End Date -->
      <van-field
        label="終了日"
        :model-value="formatDate(form.endDate)"
        placeholder="終了日を選択してください"
        readonly
        clickable
        @click="showEndDatePicker = true"
      >
        <template #left-icon>
          <van-icon name="calendar-o" />
        </template>
      </van-field>

      <!-- End Time (hidden if all-day) -->
      <van-field
        v-if="!form.isAllDay"
        label="終了時刻"
        :model-value="form.endTime"
        placeholder="終了時刻を選択してください"
        readonly
        clickable
        @click="showEndTimePicker = true"
      >
        <template #left-icon>
          <van-icon name="clock-o" />
        </template>
      </van-field>

      <!-- All Day Toggle -->
      <van-field label="終日">
        <template #input>
          <van-switch v-model="form.isAllDay" size="20" />
        </template>
      </van-field>

      <!-- Category -->
      <category-picker
        v-model="form.category"
        :rules="[{ required: true, message: 'カテゴリーを選択してください' }]"
      />

      <!-- Color -->
      <color-picker v-model="form.color" />

      <!-- Tags -->
      <van-field label="タグ">
        <template #input>
          <div class="tag-list">
            <van-tag
              v-for="(tag, index) in form.tags"
              :key="index"
              closeable
              @close="removeTag(index)"
            >
              {{ tag }}
            </van-tag>
            <van-button
              size="small"
              icon="plus"
              plain
              @click="showTagInput = true"
            >
              追加
            </van-button>
          </div>
        </template>
      </van-field>

      <!-- Reminder -->
      <van-field label="リマインダー">
        <template #input>
          <van-switch v-model="form.reminder.enabled" size="20" />
        </template>
      </van-field>

      <!-- Reminder Time (shown if reminder enabled) -->
      <van-field
        v-if="form.reminder.enabled"
        label="事前通知"
        :model-value="getReminderDisplay()"
        readonly
        clickable
        @click="showReminderPicker = true"
      >
        <template #left-icon>
          <van-icon name="bell-o" />
        </template>
      </van-field>

      <!-- Submit Buttons -->
      <div class="form-actions">
        <van-button
          block
          type="primary"
          native-type="submit"
          :loading="loading"
        >
          {{ isEdit ? 'スケジュールを更新' : 'スケジュールを作成' }}
        </van-button>
        <van-button
          v-if="showCancel"
          block
          @click="$emit('cancel')"
        >
          キャンセル
        </van-button>
      </div>
    </van-form>

    <!-- Date Pickers -->
    <van-popup v-model:show="showStartDatePicker" position="bottom" round>
      <van-date-picker
        v-model="startDateValue"
        title="開始日を選択"
        :min-date="new Date(2020, 0, 1)"
        :max-date="new Date(2030, 11, 31)"
        @confirm="handleStartDateConfirm"
        @cancel="showStartDatePicker = false"
      />
    </van-popup>

    <van-popup v-model:show="showEndDatePicker" position="bottom" round>
      <van-date-picker
        v-model="endDateValue"
        title="終了日を選択"
        :min-date="new Date(form.startDate)"
        :max-date="new Date(2030, 11, 31)"
        @confirm="handleEndDateConfirm"
        @cancel="showEndDatePicker = false"
      />
    </van-popup>

    <!-- Time Pickers -->
    <van-popup v-model:show="showStartTimePicker" position="bottom" round>
      <van-time-picker
        v-model="startTimeValue"
        title="開始時刻を選択"
        @confirm="handleStartTimeConfirm"
        @cancel="showStartTimePicker = false"
      />
    </van-popup>

    <van-popup v-model:show="showEndTimePicker" position="bottom" round>
      <van-time-picker
        v-model="endTimeValue"
        title="終了時刻を選択"
        @confirm="handleEndTimeConfirm"
        @cancel="showEndTimePicker = false"
      />
    </van-popup>

    <!-- Reminder Picker -->
    <van-popup v-model:show="showReminderPicker" position="bottom" round>
      <van-picker
        :columns="reminderOptions"
        @confirm="handleReminderConfirm"
        @cancel="showReminderPicker = false"
      />
    </van-popup>

    <!-- Tag Input Dialog -->
    <van-dialog
      v-model:show="showTagInput"
      title="タグを追加"
      show-cancel-button
      @confirm="handleAddTag"
    >
      <van-field
        v-model="newTag"
        placeholder="タグ名を入力してください"
        maxlength="10"
      />
    </van-dialog>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue'
import { getCurrentDate, getCurrentTime, formatDate as formatDateUtil } from '@/utils/date'
import { REMINDER_OPTIONS } from '@/utils/constants'
import CategoryPicker from '@/components/category/CategoryPicker.vue'
import ColorPicker from '@/components/category/ColorPicker.vue'
import { showToast } from 'vant'

// Props
const props = defineProps({
  initialData: {
    type: Object,
    default: null
  },
  isEdit: {
    type: Boolean,
    default: false
  },
  showCancel: {
    type: Boolean,
    default: true
  },
  loading: {
    type: Boolean,
    default: false
  }
})

// Emits
const emit = defineEmits(['submit', 'cancel'])

// Form state
const form = ref({
  title: '',
  description: '',
  startDate: getCurrentDate(),
  startTime: getCurrentTime(),
  endDate: getCurrentDate(),
  endTime: getCurrentTime(),
  isAllDay: false,
  category: 'personal',
  tags: [],
  color: '#FF6B6B',
  reminder: {
    enabled: true,
    type: 'local',
    time: 15,
    unit: 'minutes'
  }
})

// Picker states
const showStartDatePicker = ref(false)
const showEndDatePicker = ref(false)
const showStartTimePicker = ref(false)
const showEndTimePicker = ref(false)
const showReminderPicker = ref(false)
const showTagInput = ref(false)

// Picker values (for van-date-picker format)
const startDateValue = ref(new Date())
const endDateValue = ref(new Date())
const startTimeValue = ref(['12', '00'])
const endTimeValue = ref(['12', '00'])

// Tag input
const newTag = ref('')

// Reminder options
const reminderOptions = computed(() => {
  return REMINDER_OPTIONS.map(opt => ({
    text: opt.label,
    value: opt.value,
    unit: opt.unit
  }))
})

// Initialize form with existing data
if (props.initialData) {
  Object.assign(form.value, props.initialData)
}

/**
 * Format date for display
 */
function formatDate(date) {
  return formatDateUtil(date, 'YYYY-MM-DD')
}

/**
 * Handle start date confirm
 */
function handleStartDateConfirm(value) {
  const year = value.getFullYear()
  const month = String(value.getMonth() + 1).padStart(2, '0')
  const day = String(value.getDate()).padStart(2, '0')
  form.value.startDate = `${year}-${month}-${day}`
  showStartDatePicker.value = false

  // Auto-update end date if it's before start date
  if (form.value.endDate < form.value.startDate) {
    form.value.endDate = form.value.startDate
  }
}

/**
 * Handle end date confirm
 */
function handleEndDateConfirm(value) {
  const year = value.getFullYear()
  const month = String(value.getMonth() + 1).padStart(2, '0')
  const day = String(value.getDate()).padStart(2, '0')
  form.value.endDate = `${year}-${month}-${day}`
  showEndDatePicker.value = false
}

/**
 * Handle start time confirm
 */
function handleStartTimeConfirm(value) {
  form.value.startTime = `${value[0]}:${value[1]}`
  showStartTimePicker.value = false
}

/**
 * Handle end time confirm
 */
function handleEndTimeConfirm(value) {
  form.value.endTime = `${value[0]}:${value[1]}`
  showEndTimePicker.value = false
}

/**
 * Handle reminder confirm
 */
function handleReminderConfirm(value) {
  form.value.reminder.time = value.value
  form.value.reminder.unit = value.unit
  showReminderPicker.value = false
}

/**
 * Get reminder display text
 */
function getReminderDisplay() {
  const option = REMINDER_OPTIONS.find(
    opt => opt.value === form.value.reminder.time
  )
  return option ? option.label : '15分前'
}

/**
 * Add tag
 */
function handleAddTag() {
  const tag = newTag.value.trim()
  if (tag && !form.value.tags.includes(tag)) {
    form.value.tags.push(tag)
    newTag.value = ''
  }
}

/**
 * Remove tag
 */
function removeTag(index) {
  form.value.tags.splice(index, 1)
}

/**
 * Handle form submit
 */
function handleSubmit() {
  // Validate
  if (!form.value.title) {
    showToast('タイトルを入力してください')
    return
  }

  if (!form.value.startDate) {
    showToast('開始日を選択してください')
    return
  }

  // Emit submit event
  emit('submit', { ...form.value })
}

/**
 * Watch all-day toggle
 */
watch(() => form.value.isAllDay, (isAllDay) => {
  if (isAllDay) {
    form.value.startTime = '00:00'
    form.value.endTime = '23:59'
  }
})
</script>

<style scoped>
.schedule-editor {
  background: var(--bg-page);
}

.tag-list {
  display: flex;
  flex-wrap: wrap;
  gap: var(--spacing-sm);
  align-items: center;
}

.form-actions {
  padding: var(--spacing-lg);
  display: flex;
  flex-direction: column;
  gap: var(--spacing-md);
}
</style>

// src/components/schedule/ScheduleEditor.jsx
/**
 * ScheduleEditor.jsx - Form for creating/editing schedules
 */

import React, { useState, useEffect } from 'react'
import { getCurrentDate, getCurrentTime, formatDate as formatDateUtil } from '@/utils/date'
import { REMINDER_OPTIONS } from '@/utils/constants'
import CategoryPicker from '@/components/category/CategoryPicker'
import ColorPicker from '@/components/category/ColorPicker'

const DEFAULT_FORM = {
    title: '',
    description: '',
    startDate: getCurrentDate(),
    startTime: getCurrentTime(),
    endDate: getCurrentDate(),
    endTime: getCurrentTime(),
    isAllDay: false,
    category: 'personal',
    tags: [],
    color: '#FF6B6B',
    reminder: { enabled: true, type: 'local', time: 15, unit: 'minutes' }
}

export default function ScheduleEditor({
    initialData = null,
    isEdit = false,
    showCancel = true,
    loading = false,
    onSubmit,
    onCancel
}) {
    const [form, setForm] = useState(initialData ? { ...DEFAULT_FORM, ...initialData } : { ...DEFAULT_FORM })
    const [showReminderPicker, setShowReminderPicker] = useState(false)
    const [showTagInput, setShowTagInput] = useState(false)
    const [newTag, setNewTag] = useState('')
    const [errors, setErrors] = useState({})

    // When isAllDay changes, update times
    useEffect(() => {
        if (form.isAllDay) {
            setForm(f => ({ ...f, startTime: '00:00', endTime: '23:59' }))
        }
    }, [form.isAllDay])

    function updateForm(key, value) {
        setForm(f => {
            const updated = { ...f, [key]: value }
            // Auto-fix end date if before start date
            if (key === 'startDate' && updated.endDate < value) {
                updated.endDate = value
            }
            return updated
        })
        setErrors(e => ({ ...e, [key]: undefined }))
    }

    function updateReminder(key, value) {
        setForm(f => ({ ...f, reminder: { ...f.reminder, [key]: value } }))
    }

    function handleAddTag() {
        const tag = newTag.trim()
        if (tag && !form.tags.includes(tag)) {
            setForm(f => ({ ...f, tags: [...f.tags, tag] }))
            setNewTag('')
        }
        setShowTagInput(false)
    }

    function removeTag(index) {
        setForm(f => ({ ...f, tags: f.tags.filter((_, i) => i !== index) }))
    }

    function getReminderDisplay() {
        const opt = REMINDER_OPTIONS.find(o => o.value === form.reminder.time)
        return opt ? opt.label : '15分前'
    }

    function validate() {
        const errs = {}
        if (!form.title) errs.title = 'タイトルを入力してください'
        if (!form.startDate) errs.startDate = '開始日を選択してください'
        setErrors(errs)
        return Object.keys(errs).length === 0
    }

    function handleSubmit(e) {
        e.preventDefault()
        if (!validate()) return
        onSubmit && onSubmit({ ...form })
    }

    return (
        <div className="schedule-editor">
            <form onSubmit={handleSubmit}>
                {/* Title */}
                <div className="form-field">
                    <label className="field-label">タイトル <span className="required">*</span></label>
                    <input
                        className={`field-input ${errors.title ? 'field-error' : ''}`}
                        type="text"
                        placeholder="タイトルを入力してください"
                        value={form.title}
                        onChange={e => updateForm('title', e.target.value)}
                        maxLength={50}
                    />
                    {errors.title && <span className="error-msg">{errors.title}</span>}
                    <span className="word-count">{form.title.length}/50</span>
                </div>

                {/* Description */}
                <div className="form-field">
                    <label className="field-label">説明</label>
                    <textarea
                        className="field-input field-textarea"
                        placeholder="説明を入力してください（任意）"
                        value={form.description}
                        onChange={e => updateForm('description', e.target.value)}
                        maxLength={200}
                        rows={3}
                    />
                    <span className="word-count">{form.description.length}/200</span>
                </div>

                {/* Start Date */}
                <div className="form-field">
                    <label className="field-label">開始日 <span className="required">*</span></label>
                    <input
                        className="field-input"
                        type="date"
                        value={form.startDate}
                        onChange={e => updateForm('startDate', e.target.value)}
                    />
                </div>

                {/* Start Time */}
                {!form.isAllDay && (
                    <div className="form-field">
                        <label className="field-label">開始時刻</label>
                        <input
                            className="field-input"
                            type="time"
                            value={form.startTime}
                            onChange={e => updateForm('startTime', e.target.value)}
                        />
                    </div>
                )}

                {/* End Date */}
                <div className="form-field">
                    <label className="field-label">終了日</label>
                    <input
                        className="field-input"
                        type="date"
                        value={form.endDate}
                        min={form.startDate}
                        onChange={e => updateForm('endDate', e.target.value)}
                    />
                </div>

                {/* End Time */}
                {!form.isAllDay && (
                    <div className="form-field">
                        <label className="field-label">終了時刻</label>
                        <input
                            className="field-input"
                            type="time"
                            value={form.endTime}
                            onChange={e => updateForm('endTime', e.target.value)}
                        />
                    </div>
                )}

                {/* All Day Toggle */}
                <div className="form-field form-field-inline">
                    <label className="field-label">終日</label>
                    <label className="toggle-switch">
                        <input
                            type="checkbox"
                            checked={form.isAllDay}
                            onChange={e => updateForm('isAllDay', e.target.checked)}
                        />
                        <span className="toggle-slider" />
                    </label>
                </div>

                {/* Category */}
                <CategoryPicker
                    value={form.category}
                    onChange={val => updateForm('category', val)}
                />

                {/* Color */}
                <ColorPicker
                    value={form.color}
                    onChange={val => updateForm('color', val)}
                />

                {/* Tags */}
                <div className="form-field">
                    <label className="field-label">タグ</label>
                    <div className="tag-list">
                        {form.tags.map((tag, index) => (
                            <span key={index} className="tag tag-close">
                                {tag}
                                <button type="button" className="tag-remove" onClick={() => removeTag(index)}>×</button>
                            </span>
                        ))}
                        {!showTagInput ? (
                            <button type="button" className="btn btn-sm btn-outline" onClick={() => setShowTagInput(true)}>
                                + 追加
                            </button>
                        ) : (
                            <div className="tag-input-row">
                                <input
                                    className="field-input tag-input"
                                    type="text"
                                    placeholder="タグ名"
                                    value={newTag}
                                    maxLength={10}
                                    onChange={e => setNewTag(e.target.value)}
                                    onKeyDown={e => e.key === 'Enter' && handleAddTag()}
                                    autoFocus
                                />
                                <button type="button" className="btn btn-sm btn-primary" onClick={handleAddTag}>追加</button>
                                <button type="button" className="btn btn-sm" onClick={() => { setShowTagInput(false); setNewTag('') }}>×</button>
                            </div>
                        )}
                    </div>
                </div>

                {/* Reminder Toggle */}
                <div className="form-field form-field-inline">
                    <label className="field-label">リマインダー</label>
                    <label className="toggle-switch">
                        <input
                            type="checkbox"
                            checked={form.reminder.enabled}
                            onChange={e => updateReminder('enabled', e.target.checked)}
                        />
                        <span className="toggle-slider" />
                    </label>
                </div>

                {/* Reminder Time */}
                {form.reminder.enabled && (
                    <div className="form-field" onClick={() => setShowReminderPicker(true)}>
                        <label className="field-label">事前通知</label>
                        <div className="field-input field-clickable">
                            <span>🔔 {getReminderDisplay()}</span>
                            <span className="field-arrow">›</span>
                        </div>
                    </div>
                )}

                {/* Submit Buttons */}
                <div className="form-actions">
                    <button type="submit" className="btn btn-primary btn-block" disabled={loading}>
                        {loading ? '保存中...' : (isEdit ? 'スケジュールを更新' : 'スケジュールを作成')}
                    </button>
                    {showCancel && (
                        <button type="button" className="btn btn-block" onClick={onCancel}>
                            キャンセル
                        </button>
                    )}
                </div>
            </form>

            {/* Reminder Picker */}
            {showReminderPicker && (
                <div className="popup-overlay" onClick={() => setShowReminderPicker(false)}>
                    <div className="popup-sheet popup-sheet-sm" onClick={e => e.stopPropagation()}>
                        <div className="picker-header">
                            <button className="btn btn-text" onClick={() => setShowReminderPicker(false)}>
                                キャンセル
                            </button>
                            <span className="picker-title">事前通知</span>
                        </div>
                        <div className="picker-options">
                            {REMINDER_OPTIONS.map(opt => (
                                <div
                                    key={opt.value}
                                    className={`picker-option ${form.reminder.time === opt.value ? 'is-selected' : ''}`}
                                    onClick={() => {
                                        updateReminder('time', opt.value)
                                        updateReminder('unit', opt.unit)
                                        setShowReminderPicker(false)
                                    }}
                                >
                                    {opt.label}
                                    {form.reminder.time === opt.value && <span> ✓</span>}
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            )}
        </div>
    )
}
