// src/components/category/ColorPicker.jsx
/**
 * ColorPicker.jsx - Color selection component
 */

import React, { useState } from 'react'

const COLOR_OPTIONS = [
    '#FF6B6B', '#FF9FF3', '#FFE66D', '#FFB84D',
    '#4ECDC4', '#95E1D3', '#06C755', '#A8E6CF',
    '#5DADE2', '#C7CEEA', '#9B59B6', '#E74C3C',
    '#3498DB', '#1ABC9C', '#F39C12', '#B0B0B0'
]

export default function ColorPicker({ value, onChange, label = '色' }) {
    const [showPicker, setShowPicker] = useState(false)
    const [tempColor, setTempColor] = useState(value)

    function handleConfirm() {
        onChange && onChange(tempColor)
        setShowPicker(false)
    }

    function handleOpen() {
        setTempColor(value)
        setShowPicker(true)
    }

    return (
        <>
            <div className="form-field" onClick={handleOpen}>
                <label className="field-label">{label}</label>
                <div className="field-input field-clickable">
                    <div className="color-preview">
                        <div className="color-swatch" style={{ backgroundColor: value }} />
                        <span>{value}</span>
                    </div>
                    <span className="field-arrow">›</span>
                </div>
            </div>

            {showPicker && (
                <div className="popup-overlay" onClick={() => setShowPicker(false)}>
                    <div className="popup-sheet popup-sheet-sm" onClick={e => e.stopPropagation()}>
                        <div className="picker-header">
                            <button className="btn btn-text" onClick={() => setShowPicker(false)}>
                                キャンセル
                            </button>
                            <span className="picker-title">色を選択</span>
                            <button className="btn btn-text btn-primary-text" onClick={handleConfirm}>
                                確定
                            </button>
                        </div>

                        <div className="color-grid">
                            {COLOR_OPTIONS.map(color => (
                                <div
                                    key={color}
                                    className={`color-option ${tempColor === color ? 'is-selected' : ''}`}
                                    style={{ backgroundColor: color }}
                                    onClick={() => setTempColor(color)}
                                >
                                    {tempColor === color && <span className="color-check">✓</span>}
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            )}
        </>
    )
}

// src/components/category/ColorPicker.vue
<template>
  <van-field
    :label="label"
    readonly
    clickable
    @click="showPicker = true"
  >
    <template #input>
      <div class="color-preview">
        <div
          class="color-swatch"
          :style="{ backgroundColor: modelValue }"
        />
        <span>{{ modelValue }}</span>
      </div>
    </template>
    <template #right-icon>
      <van-icon name="arrow" />
    </template>
  </van-field>

  <!-- Color picker popup -->
  <van-popup
    v-model:show="showPicker"
    position="bottom"
    round
    :style="{ height: '40%' }"
  >
    <div class="color-picker-popup">
      <div class="picker-header">
        <van-button text @click="showPicker = false">キャンセル</van-button>
        <span class="picker-title">色を選択</span>
        <van-button type="primary" text @click="handleConfirm">確定</van-button>
      </div>

      <div class="color-grid">
        <div
          v-for="color in colorOptions"
          :key="color"
          class="color-option"
          :class="{ 'is-selected': tempColor === color }"
          :style="{ backgroundColor: color }"
          @click="tempColor = color"
        >
          <van-icon
            v-if="tempColor === color"
            name="success"
            color="white"
            size="20"
          />
        </div>
      </div>
    </div>
  </van-popup>
</template>

<script setup>
import { ref } from 'vue'

// Props
const props = defineProps({
  modelValue: {
    type: String,
    default: '#FF6B6B'
  },
  label: {
    type: String,
    default: '色'
  }
})

// Emits
const emit = defineEmits(['update:modelValue'])

// Local state
const showPicker = ref(false)
const tempColor = ref(props.modelValue)

// Predefined color palette
const colorOptions = [
  '#FF6B6B', // Red
  '#FF9FF3', // Pink
  '#FFE66D', // Yellow
  '#FFB84D', // Orange
  '#4ECDC4', // Teal
  '#95E1D3', // Mint
  '#06C755', // Green
  '#A8E6CF', // Light green
  '#5DADE2', // Blue
  '#C7CEEA', // Lavender
  '#9B59B6', // Purple
  '#E74C3C', // Dark red
  '#3498DB', // Sky blue
  '#1ABC9C', // Turquoise
  '#F39C12', // Gold
  '#B0B0B0'  // Gray
]

/**
 * Handle confirm selection
 */
function handleConfirm() {
  emit('update:modelValue', tempColor.value)
  showPicker.value = false
}
</script>

<style scoped>
.color-preview {
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
}

.color-swatch {
  width: 32px;
  height: 32px;
  border-radius: var(--radius-md);
  border: 2px solid var(--border-color);
  box-shadow: var(--shadow-sm);
}

.color-picker-popup {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.picker-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: var(--spacing-md);
  border-bottom: 1px solid var(--border-color);
}

.picker-title {
  font-size: var(--font-lg);
  font-weight: var(--font-semibold);
  color: var(--text-primary);
}

.color-grid {
  flex: 1;
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: var(--spacing-md);
  padding: var(--spacing-lg);
  overflow-y: auto;
}

.color-option {
  aspect-ratio: 1;
  border-radius: var(--radius-lg);
  border: 3px solid transparent;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all var(--transition-fast);
  box-shadow: var(--shadow-sm);
}

.color-option:hover {
  transform: scale(1.05);
  box-shadow: var(--shadow-md);
}

.color-option.is-selected {
  border-color: var(--text-primary);
  box-shadow: 0 0 0 4px rgba(0, 0, 0, 0.1);
}
</style>
