// src/views/ScheduleCreate.jsx
/**
 * ScheduleCreate.jsx - Create new schedule view
 */

import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useScheduleStore } from '@/stores/scheduleStore'
import ScheduleEditor from '@/components/schedule/ScheduleEditor'

export default function ScheduleCreate() {
    const navigate = useNavigate()
    const scheduleStore = useScheduleStore()
    const [loading, setLoading] = useState(false)

    async function handleSubmit(formData) {
        setLoading(true)
        try {
            await scheduleStore.createSchedule(formData)
            alert('作成しました')
            navigate(-1)
        } catch (error) {
            alert(error.message || '作成できませんでした')
        } finally {
            setLoading(false)
        }
    }

    function handleBack() {
        navigate(-1)
    }

    return (
        <div className="schedule-create-view">
            <div className="nav-bar">
                <button className="nav-back btn btn-icon" onClick={handleBack}>‹</button>
                <h2 className="nav-title">スケジュールを作成</h2>
            </div>

            <ScheduleEditor
                loading={loading}
                onSubmit={handleSubmit}
                onCancel={handleBack}
            />
        </div>
    )
}

// src/views/ScheduleCreate.vue
<template>
  <div class="schedule-create-view">
    <van-nav-bar
      title="スケジュールを作成"
      left-arrow
      @click-left="handleBack"
    />

    <schedule-editor
      :loading="loading"
      @submit="handleSubmit"
      @cancel="handleBack"
    />
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useScheduleStore } from '@/stores/schedule'
import { showToast } from 'vant'
import ScheduleEditor from '@/components/schedule/ScheduleEditor.vue'

// Router
const router = useRouter()

// Store
const scheduleStore = useScheduleStore()

// State
const loading = ref(false)

/**
 * Handle form submit
 */
async function handleSubmit(formData) {
  loading.value = true

  try {
    await scheduleStore.createSchedule(formData)
    showToast('作成しました')

    // Navigate back
    router.back()
  } catch (error) {
    showToast(error.message || '作成できませんでした')
  } finally {
    loading.value = false
  }
}

/**
 * Handle back navigation
 */
function handleBack() {
  router.back()
}
</script>

<style scoped>
.schedule-create-view {
  min-height: 100vh;
  background: var(--bg-page);
}
</style>
