// src/views/ScheduleList.jsx
/**
 * ScheduleList.jsx - Schedule list view
 */

import React, { useEffect } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useScheduleStore } from '@/stores/scheduleStore'
import ScheduleListComponent from '@/components/schedule/ScheduleList'
import { formatDate } from '@/utils/date'

export default function ScheduleList() {
    const navigate = useNavigate()
    const [searchParams, setSearchParams] = useSearchParams()
    const scheduleStore = useScheduleStore()

    useEffect(() => {
        const date = searchParams.get('date')
        const category = searchParams.get('category')
        const q = searchParams.get('q')

        scheduleStore.setFilterDate(date || null)
        scheduleStore.setFilterCategory(category || null)
        scheduleStore.setSearchQuery(q || '')
    }, [])

    function clearDateFilter() {
        scheduleStore.setFilterDate(null)
        const params = new URLSearchParams(searchParams)
        params.delete('date')
        setSearchParams(params)
    }

    function handleScheduleClick(schedule) {
        if (schedule?.id) navigate(`/schedule/${schedule.id}`)
    }

    function handleScheduleEdit(schedule) {
        navigate(`/schedule/${schedule.id}/edit`)
    }

    function handleCreate() {
        navigate('/schedule/create')
    }

    return (
        <div className="schedule-list-view">
            <div className="nav-bar">
                <h2 className="nav-title">スケジュール一覧</h2>
                <button className="nav-action btn btn-icon" onClick={handleCreate}>+</button>
            </div>

            {scheduleStore.filterDate && (
                <div className="active-filters">
                    <span className="tag tag-primary">
                        {formatDate(scheduleStore.filterDate)} のスケジュール
                    </span>
                    <button className="btn btn-sm btn-outline" onClick={clearDateFilter}>
                        クリア
                    </button>
                </div>
            )}

            <ScheduleListComponent
                loading={scheduleStore.loading}
                onScheduleClick={handleScheduleClick}
                onScheduleEdit={handleScheduleEdit}
                onCreate={handleCreate}
            />
        </div>
    )
}

// src/views/ScheduleList.vue
<template>
  <div class="schedule-list-view">
    <van-nav-bar title="スケジュール一覧">
      <template #right>
        <van-icon name="plus" size="20" @click="handleCreate" />
      </template>
    </van-nav-bar>

    <div v-if="scheduleStore.filterDate" class="active-filters">
      <van-tag type="primary" plain>
        {{ formatDate(scheduleStore.filterDate) }} のスケジュール
      </van-tag>
      <van-button size="small" plain @click="clearDateFilter">
        クリア
      </van-button>
    </div>

    <schedule-list
      :loading="scheduleStore.loading"
      @schedule-click="handleScheduleClick"
      @schedule-edit="handleScheduleEdit"
      @create="handleCreate"
    />
  </div>
</template>

<script setup>
import { onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useScheduleStore } from '@/stores/schedule'
import ScheduleList from '@/components/schedule/ScheduleList.vue'
import { formatDate } from '@/utils/date'

// Router
const router = useRouter()
const route = useRoute()

// Store
const scheduleStore = useScheduleStore()

/**
 * Handle schedule click
 */
function handleScheduleClick(schedule) {
  console.log('Schedule clicked:', schedule)
  if (schedule?.id) {
    router.push(`/schedule/${schedule.id}`)
  }
}

/**
 * Handle schedule edit
 */
function handleScheduleEdit(schedule) {
  router.push(`/schedule/${schedule.id}/edit`)
}

/**
 * Handle create schedule
 */
function handleCreate() {
  router.push('/schedule/create')
}

function clearDateFilter() {
  scheduleStore.setFilterDate(null)
  const query = { ...route.query }
  delete query.date
  router.replace({ query })
}

onMounted(() => {
  const { date, category, q } = route.query

  scheduleStore.setFilterDate(date ? String(date) : null)

  scheduleStore.setFilterCategory(category ? String(category) : null)

  scheduleStore.setSearchQuery(q ? String(q) : '')
})
</script>

<style scoped>
.schedule-list-view {
  min-height: 100vh;
  background: var(--bg-page);
}

.active-filters {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--spacing-sm);
  padding: var(--spacing-sm) var(--spacing-md);
  background: var(--bg-card);
  border-bottom: 1px solid var(--border-color);
}
</style>
